### ISSUE TITLE
Obscure systems

### ISSUE THREAD

**Issue by dievsky** [JetBrains-Research/simdstat#13]
What if our library encounters a processor which does not support SSE2? Our dispatch strategy assumes that only AVX support is in question. The library would load successfully and fail with a SIGILL on any invocation. This scenario looks extremely hypothetical for x86 family, of course, but I can easily enough imagine a laptop running on ARM.

**Comment by olegs** [comment]
@dievsky Adding note to requirements and closing?

**Comment by dievsky** [comment]
@olegs Sounds good.

**Comment by dievsky** [comment]
Added a note, closing.
