### ISSUE TITLE
dep-boost.sh does not work on gentoo linux

### ISSUE THREAD

**Issue by VladRassokhin** [JetBrains-Research/simdstat#16]
Got output: 
```text
./deb-boost.sh: line 14: dch: command not found
ionice: failed to execute debuild: No such file or directory
```
Please improve script or requirements documentation

**Comment by olegs** [comment]
@VladRassokhin simdstat is being build using docker at the moment. Couldn't setup docker build on public teamcity, is it available?

**Comment by olegs** [comment]
Closing the issue due to Docker and #14.
